version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: reusable
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  mysql-data: