spring:
  application:
    name: reusableServer

  datasource:
    url: jdbc:mysql://localhost:3306/reusable?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: user
    password: user1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 3000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect